/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import com.formdev.flatlaf.FlatClientProperties;
import com.formdev.flatlaf.extras.FlatSVGIcon;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import model.GRNItem;
import model.MySQL;
import raven.toast.Notifications;

/**
 *
 * @author User
 */
public class GRN extends javax.swing.JFrame {

    private static Home home = new Home();
    private static GRNItem grnItem = new GRNItem();
    private static Products products = new Products();
    private static SignIn signIn;
    private static String user;

    /**
     * Creates new form GRN
     */
    public GRN() {
        initComponents();
        this.setExtendedState(Home.MAXIMIZED_BOTH);
        init();
        styleTheTextFieldsAndButtons();
        generateGRNId();
        calTotal();
        getBalance();

        // set notification position
        Notifications.getInstance();

        //disable buttons
        total_lable.setEnabled(false);
        balance_label.setEnabled(false);

        // add a icon image
        Image image = Toolkit.getDefaultToolkit().getImage(this.getClass().getResource("/resources/icon.png"));
        this.setIconImage(image);

        // set the table details center
        DefaultTableCellRenderer renderer = new DefaultTableCellRenderer();
        renderer.setHorizontalAlignment(SwingConstants.CENTER);

        jTable1.setDefaultRenderer(Object.class, renderer);
    }

    // set supplier details
    public void setSupplierDetails() {
        jLabel5.setText(grnItem.getSupplier_email());
        jLabel9.setText(grnItem.getSupplier_name());
    }

    // set supplier details
    public void setMaterialsDetails() {
        jLabel11.setText(grnItem.getMaterial_id());
        jLabel15.setText(grnItem.getMaterial_name());
    }

    // get use email with a bean
    public void getUserEmail(SignIn signIn) {
        this.signIn = signIn;
        if (!(this.signIn.getUser() == null)) {
            user = this.signIn.getUser();
            jLabel3.setText(user);
        }
    }

    // store the email staticly
    @Override
    public void setVisible(boolean b) {
        super.setVisible(b);
        if (b && user != null) {
            jLabel3.setText(user);
        }
    }

    // genarate unique GRN Id
    private void generateGRNId() {
        long id = System.currentTimeMillis();
        jLabel6.setText(String.valueOf(id));
    }

    // style the text fields and buttons
    private void styleTheTextFieldsAndButtons() {
        qty.putClientProperty("JComponent.roundRect", true);
        qty.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Quantity");
        qty.putClientProperty(FlatClientProperties.STYLE, "margin:0, 20, 0, 20");
        qty.putClientProperty(FlatClientProperties.TEXT_FIELD_SHOW_CLEAR_BUTTON, true);

        unit_price.putClientProperty("JComponent.roundRect", true);
        unit_price.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Unit Price");
        unit_price.putClientProperty(FlatClientProperties.STYLE, "margin:0, 20, 0, 20");
        unit_price.putClientProperty(FlatClientProperties.TEXT_FIELD_SHOW_CLEAR_BUTTON, true);

        total_lable.putClientProperty("JComponent.roundRect", true);
        total_lable.putClientProperty(FlatClientProperties.STYLE, "margin:0, 20, 0, 20");

        paying_price.putClientProperty("JComponent.roundRect", true);
        paying_price.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Paying Price");
        paying_price.putClientProperty(FlatClientProperties.STYLE, "margin:0, 20, 0, 20");

        balance_label.putClientProperty("JComponent.roundRect", true);
        balance_label.putClientProperty(FlatClientProperties.STYLE, "margin:0, 20, 0, 20");

        selectSupplier.putClientProperty("JButton.buttonType", "roundRect");
        selectMaterial.putClientProperty("JButton.buttonType", "roundRect");
        addtogrn.putClientProperty("JButton.buttonType", "roundRect");
        clear.putClientProperty("JButton.buttonType", "roundRect");
        savegrn.putClientProperty("JButton.buttonType", "roundRect");
    }

    private void init() {
        // icons, logos & images load
        FlatSVGIcon back = new FlatSVGIcon("resources//backTo.svg", 38, 34);
        back_label.setIcon(back);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        backLogo = new javax.swing.JPanel();
        back_label = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        selectSupplier = new javax.swing.JButton();
        selectMaterial = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        qty = new javax.swing.JFormattedTextField();
        unit_price = new javax.swing.JFormattedTextField();
        addtogrn = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        savegrn = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        paying_price = new javax.swing.JFormattedTextField();
        jLabel26 = new javax.swing.JLabel();
        balance_label = new javax.swing.JFormattedTextField();
        total_lable = new javax.swing.JFormattedTextField();
        clearAll = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jScrollPane2.setBorder(null);
        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jPanel2.setPreferredSize(new java.awt.Dimension(1240, 1128));

        jLabel14.setBackground(new java.awt.Color(121, 203, 96));
        jLabel14.setFont(new java.awt.Font("Retro Signed", 0, 66)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("GOODS RECEIVED NOTE");
        jLabel14.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 229, 255), 3, true));
        jLabel14.setOpaque(true);

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        backLogo.setBackground(new java.awt.Color(121, 203, 96));
        backLogo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 229, 255), 3, true));
        backLogo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backLogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backLogobackToHome(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("JetBrains Mono ExtraBold", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Back");

        javax.swing.GroupLayout backLogoLayout = new javax.swing.GroupLayout(backLogo);
        backLogo.setLayout(backLogoLayout);
        backLogoLayout.setHorizontalGroup(
            backLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backLogoLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(back_label, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                .addGap(10, 10, 10))
        );
        backLogoLayout.setVerticalGroup(
            backLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
            .addComponent(back_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel4.setBackground(new java.awt.Color(204, 229, 255));
        jPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(121, 203, 96), 3, true));

        jLabel3.setFont(new java.awt.Font("JetBrains Mono SemiBold", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("JetBrains Mono ExtraBold", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText(" Employee Email :-");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel5.setBackground(new java.awt.Color(204, 229, 255));
        jPanel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(121, 203, 96), 3, true));

        jLabel6.setFont(new java.awt.Font("JetBrains Mono SemiBold", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));

        jLabel7.setFont(new java.awt.Font("JetBrains Mono ExtraBold", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText(" GRN Number :-");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        selectSupplier.setFont(new java.awt.Font("JetBrains Mono ExtraBold", 1, 18)); // NOI18N
        selectSupplier.setForeground(new java.awt.Color(0, 0, 0));
        selectSupplier.setText("Select Supplier");
        selectSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectSupplierActionPerformed(evt);
            }
        });

        selectMaterial.setFont(new java.awt.Font("JetBrains Mono ExtraBold", 1, 18)); // NOI18N
        selectMaterial.setForeground(new java.awt.Color(0, 0, 0));
        selectMaterial.setText("Select Material");
        selectMaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectMaterialActionPerformed(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(121, 203, 96));
        jLabel4.setFont(new java.awt.Font("JetBrains Mono ExtraBold", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText(" Supplier Email :-");
        jLabel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 229, 255), 3, true));
        jLabel4.setOpaque(true);

        jLabel5.setBackground(new java.awt.Color(121, 203, 96));
        jLabel5.setFont(new java.awt.Font("JetBrains Mono SemiBold", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 229, 255), 3, true));
        jLabel5.setOpaque(true);

        jLabel8.setBackground(new java.awt.Color(121, 203, 96));
        jLabel8.setFont(new java.awt.Font("JetBrains Mono ExtraBold", 1, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText(" Supplier Name :-");
        jLabel8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 229, 255), 3, true));
        jLabel8.setOpaque(true);

        jLabel9.setBackground(new java.awt.Color(121, 203, 96));
        jLabel9.setFont(new java.awt.Font("JetBrains Mono SemiBold", 1, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 229, 255), 3, true));
        jLabel9.setOpaque(true);

        jLabel10.setBackground(new java.awt.Color(121, 203, 96));
        jLabel10.setFont(new java.awt.Font("JetBrains Mono ExtraBold", 1, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText(" Material ID :-");
        jLabel10.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 229, 255), 3, true));
        jLabel10.setOpaque(true);

        jLabel11.setBackground(new java.awt.Color(121, 203, 96));
        jLabel11.setFont(new java.awt.Font("JetBrains Mono SemiBold", 1, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 229, 255), 3, true));
        jLabel11.setOpaque(true);

        jLabel13.setBackground(new java.awt.Color(121, 203, 96));
        jLabel13.setFont(new java.awt.Font("JetBrains Mono ExtraBold", 1, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText(" Material Name :-");
        jLabel13.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 229, 255), 3, true));
        jLabel13.setOpaque(true);

        jLabel15.setBackground(new java.awt.Color(121, 203, 96));
        jLabel15.setFont(new java.awt.Font("JetBrains Mono SemiBold", 1, 16)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 229, 255), 3, true));
        jLabel15.setOpaque(true);

        jLabel16.setBackground(new java.awt.Color(121, 203, 96));
        jLabel16.setFont(new java.awt.Font("JetBrains Mono ExtraBold", 1, 16)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText(" GRN Material Qty :-");
        jLabel16.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 229, 255), 3, true));
        jLabel16.setOpaque(true);

        jLabel17.setBackground(new java.awt.Color(121, 203, 96));
        jLabel17.setFont(new java.awt.Font("JetBrains Mono ExtraBold", 1, 16)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText(" GRN Material Price :-");
        jLabel17.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 229, 255), 3, true));
        jLabel17.setOpaque(true);

        qty.setForeground(new java.awt.Color(0, 0, 0));
        qty.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        qty.setText("0");
        qty.setFont(new java.awt.Font("JetBrains Mono SemiBold", 1, 16)); // NOI18N

        unit_price.setForeground(new java.awt.Color(0, 0, 0));
        unit_price.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        unit_price.setText("0");
        unit_price.setFont(new java.awt.Font("JetBrains Mono SemiBold", 1, 16)); // NOI18N

        addtogrn.setFont(new java.awt.Font("JetBrains Mono ExtraBold", 1, 20)); // NOI18N
        addtogrn.setForeground(new java.awt.Color(0, 0, 0));
        addtogrn.setText("Add to GRN");
        addtogrn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addtogrnActionPerformed(evt);
            }
        });

        clear.setFont(new java.awt.Font("JetBrains Mono ExtraBold", 1, 20)); // NOI18N
        clear.setForeground(new java.awt.Color(0, 0, 0));
        clear.setText("Clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 229, 255), 3, true));

        jTable1.setBackground(new java.awt.Color(215, 249, 204));
        jTable1.setFont(new java.awt.Font("JetBrains Mono ExtraBold", 1, 14)); // NOI18N
        jTable1.setForeground(new java.awt.Color(0, 0, 0));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Supplier Email", "Material ID", "Material Name", "GRN Material Qty", "GRN Material Unit Price", "GRN Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        jPanel6.setBackground(new java.awt.Color(121, 203, 96));
        jPanel6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 229, 255), 3, true));

        savegrn.setFont(new java.awt.Font("JetBrains Mono ExtraBold", 1, 20)); // NOI18N
        savegrn.setForeground(new java.awt.Color(0, 0, 0));
        savegrn.setText("Save GRN");
        savegrn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savegrnActionPerformed(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("JetBrains Mono ExtraBold", 1, 16)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 0, 0));
        jLabel23.setText(" Balance :-");

        jLabel24.setFont(new java.awt.Font("JetBrains Mono ExtraBold", 1, 16)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 0, 0));
        jLabel24.setText(" Paying Price :-");

        paying_price.setForeground(new java.awt.Color(0, 0, 0));
        paying_price.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        paying_price.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        paying_price.setFont(new java.awt.Font("JetBrains Mono SemiBold", 1, 16)); // NOI18N
        paying_price.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                paying_priceKeyReleased(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("JetBrains Mono ExtraBold", 1, 16)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 0, 0));
        jLabel26.setText(" Total :-");

        balance_label.setForeground(new java.awt.Color(0, 0, 0));
        balance_label.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        balance_label.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        balance_label.setFont(new java.awt.Font("JetBrains Mono SemiBold", 1, 16)); // NOI18N

        total_lable.setForeground(new java.awt.Color(0, 0, 0));
        total_lable.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        total_lable.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        total_lable.setFont(new java.awt.Font("JetBrains Mono SemiBold", 1, 16)); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(savegrn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                                .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(paying_price, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE)
                            .addComponent(balance_label, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE)
                            .addComponent(total_lable, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE))))
                .addGap(10, 10, 10))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(total_lable, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(paying_price, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(balance_label, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(savegrn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );

        clearAll.setBackground(new java.awt.Color(121, 203, 96));
        clearAll.setFont(new java.awt.Font("JetBrains Mono ExtraBold", 1, 20)); // NOI18N
        clearAll.setForeground(new java.awt.Color(0, 0, 0));
        clearAll.setText("CLEAR ALL");
        clearAll.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 229, 255), 3, true));
        clearAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearAllActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(clearAll, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(12, 12, 12)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(backLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(12, 12, 12)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(qty, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(addtogrn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(selectSupplier, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 110, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(12, 12, 12)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(unit_price, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)))
                            .addComponent(clear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(selectMaterial, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(20, 20, 20))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(backLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(selectMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selectSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                            .addComponent(qty)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                            .addComponent(unit_price))))
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addtogrn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clear, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clearAll, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        jScrollPane2.setViewportView(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1260, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backLogobackToHome(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backLogobackToHome
        //  back to home
        normalReset();
        fullReset();
        generateGRNId();
        this.dispose();
        home.setVisible(true);
    }//GEN-LAST:event_backLogobackToHome

    private void selectSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectSupplierActionPerformed
        // open select supplier JFrame Form
        this.setEnabled(false);
        GRNSelectSupplier grnSelectSupplier = new GRNSelectSupplier(this, grnItem);
        grnSelectSupplier.setVisible(true);
    }//GEN-LAST:event_selectSupplierActionPerformed

    private void selectMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectMaterialActionPerformed
        // open select material JFrame Form
        this.setEnabled(false);
        GRNSelectMaterial grnSelectMaterial = new GRNSelectMaterial(this, grnItem);
        grnSelectMaterial.setVisible(true);
    }//GEN-LAST:event_selectMaterialActionPerformed

    private void addtogrnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addtogrnActionPerformed

        // add the grn to the table
        String employee_email = jLabel3.getText();
        String grn_number = jLabel6.getText();
        String supplier_email = jLabel5.getText();
        String supplier_name = jLabel9.getText();
        String material_id = jLabel11.getText();
        String material_name = jLabel15.getText();
        String grn_material_qty = qty.getText();
        String grn_material_price = unit_price.getText();

        if (employee_email.isEmpty()) {
            Notifications.getInstance().show(Notifications.Type.ERROR, Notifications.Location.TOP_RIGHT, 3500l, "Something went wrong!");
        } else if (grn_number.isEmpty()) {
            Notifications.getInstance().show(Notifications.Type.ERROR, Notifications.Location.TOP_RIGHT, 3500l, "Something went wrong!");
        } else if (supplier_email.isEmpty()) {
            Notifications.getInstance().show(Notifications.Type.ERROR, Notifications.Location.TOP_RIGHT, 3500l, "Please select a Supplier!");
        } else if (supplier_name.isEmpty()) {
            Notifications.getInstance().show(Notifications.Type.ERROR, Notifications.Location.TOP_RIGHT, 3500l, "Please select a Supplier!");
        } else if (material_id.isEmpty()) {
            Notifications.getInstance().show(Notifications.Type.ERROR, Notifications.Location.TOP_RIGHT, 3500l, "Please select a Material!");
        } else if (material_name.isEmpty()) {
            Notifications.getInstance().show(Notifications.Type.ERROR, Notifications.Location.TOP_RIGHT, 3500l, "Please select a Material!");
        } else if (grn_material_qty.isEmpty() || grn_material_qty.equals("0") || grn_material_qty.equals("0.00")) {
            Notifications.getInstance().show(Notifications.Type.ERROR, Notifications.Location.TOP_RIGHT, 3500l, "Please enter the GRN Material Quantity!");
        } else if (!grn_material_qty.matches("^[0-9]+(\\.[0-9]{1,2})?$")) {
            Notifications.getInstance().show(Notifications.Type.ERROR, Notifications.Location.TOP_RIGHT, 3500l, "Invalid GRN Material Quantity!");
        } else if (grn_material_price.isEmpty() || grn_material_price.equals("0") || grn_material_price.equals("0.00")) {
            Notifications.getInstance().show(Notifications.Type.ERROR, Notifications.Location.TOP_RIGHT, 3500l, "Please enter the GRN Material Unit Price!");
        } else if (!grn_material_price.matches("^[0-9]+(\\.[0-9]{1,2})?$")) {
            Notifications.getInstance().show(Notifications.Type.ERROR, Notifications.Location.TOP_RIGHT, 3500l, "Invalid GRN Material Price!");
        } else {

            selectSupplier.setEnabled(false);

            try {

                double grn_qty = Double.parseDouble(grn_material_qty);
                double grn_price = Double.parseDouble(grn_material_price);

                boolean MaterialExists = false;

                DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();

                for (int i = 0; i < dtm.getRowCount(); i++) {
                    if (String.valueOf(dtm.getValueAt(i, 1)).equals(material_id)) {

                        double existingQty = Double.parseDouble(String.valueOf(dtm.getValueAt(i, 3)));

                        double updatedQty = existingQty + grn_qty;
                        double updatedPrice = grn_price;

                        double updatedTotal = updatedQty * updatedPrice;

                        dtm.setValueAt(String.valueOf(updatedQty), i, 3);
                        dtm.setValueAt(String.valueOf(updatedPrice), i, 4);
                        dtm.setValueAt(String.valueOf(updatedTotal), i, 5);

                        MaterialExists = true;
                        break;
                    }
                }

                if (!MaterialExists) {

                    Vector<String> vector = new Vector<>();
                    vector.add(supplier_email);
                    vector.add(material_id);
                    vector.add(material_name);
                    vector.add(String.valueOf(grn_qty));
                    vector.add(String.valueOf(grn_price));
                    vector.add(String.valueOf(grn_qty * grn_price));

                    dtm.addRow(vector);

                }

                jTable1.setModel(dtm);
                Notifications.getInstance().show(Notifications.Type.SUCCESS, Notifications.Location.TOP_RIGHT, 3500l, "GRN added Successfully!");
                normalReset();
                calTotal();
                getBalance();

            } catch (Exception e) {
                e.printStackTrace();
            }

        }

    }//GEN-LAST:event_addtogrnActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // normal reset
        normalReset();
        calTotal();
        getBalance();
    }//GEN-LAST:event_clearActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

        // get a values to row
        if (evt.getClickCount() == 2) {

            int row = jTable1.getSelectedRow();

            String materialID = String.valueOf(jTable1.getValueAt(row, 1));
            String materialName = String.valueOf(jTable1.getValueAt(row, 2));
            String GRNQty = String.valueOf(jTable1.getValueAt(row, 3));
            String GRNUnitPrice = String.valueOf(jTable1.getValueAt(row, 4));

            jLabel11.setText(materialID);
            jLabel15.setText(materialName);
            qty.setText(GRNQty);
            unit_price.setText(GRNUnitPrice);

            jTable1.setEnabled(false);

        }

    }//GEN-LAST:event_jTable1MouseClicked

    private void paying_priceKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_paying_priceKeyReleased
        // enter the paying price and get a balance
        getBalance();
    }//GEN-LAST:event_paying_priceKeyReleased

    private void savegrnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savegrnActionPerformed

        // save the grn
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();

        if (dtm.getRowCount() == 0) {
            Notifications.getInstance().show(Notifications.Type.ERROR, Notifications.Location.TOP_RIGHT, 3500l, "Please add a GRN to the Table!");
        } else {

            String employee_email = jLabel3.getText();
            String grn_number = jLabel6.getText();
            String paying = paying_price.getText();
            String supplier_email = jLabel5.getText();

            if (employee_email.isEmpty()) {
                Notifications.getInstance().show(Notifications.Type.ERROR, Notifications.Location.TOP_RIGHT, 3500l, "Something went wrong!");
            } else if (grn_number.isEmpty()) {
                Notifications.getInstance().show(Notifications.Type.ERROR, Notifications.Location.TOP_RIGHT, 3500l, "Something went wrong!");
            } else if (paying.isEmpty() || paying.equals("0") || paying.equals("0.00")) {
                Notifications.getInstance().show(Notifications.Type.ERROR, Notifications.Location.TOP_RIGHT, 3500l, "Please enter the Paying Price!");
            } else if (!paying.matches("^[0-9]+(\\.[0-9]{1,2})?$")) {
                Notifications.getInstance().show(Notifications.Type.ERROR, Notifications.Location.TOP_RIGHT, 3500l, "Invalid Price!");
            } else {

                double payingValue = Double.parseDouble(paying);

                try {

                    ResultSet resultSet = MySQL.executeSearch("SELECT * FROM `grn` WHERE `id` = '" + grn_number + "'");

                    if (resultSet.next()) {
                        Notifications.getInstance().show(Notifications.Type.ERROR, Notifications.Location.TOP_RIGHT, 3500l, "Something went wrong!");
                    } else {

                        String date = new SimpleDateFormat("yyyy-MM-dd").format(new Date());

                        MySQL.executeIUD("INSERT INTO `grn` (`id`,`date`,`paid_amount`,`supplier_email`,`employee_email`) VALUES "
                                + "('" + grn_number + "', '" + date + "', '" + payingValue + "', '" + supplier_email + "', '" + employee_email + "')");

                        ResultSet resultSet1 = MySQL.executeSearch("SELECT * FROM `stock`");

                        for (int i = 0; i < dtm.getRowCount(); i++) {

                            String material_id = String.valueOf(jTable1.getValueAt(i, 1));
                            String grn_material_qty = String.valueOf(jTable1.getValueAt(i, 3));
                            double grn_material_qty_value = Double.parseDouble(grn_material_qty);

                            boolean insert = true;

                            while (resultSet1.next()) {

                                if (material_id.equals(resultSet1.getString("material_id"))) {

                                    MySQL.executeIUD("UPDATE `stock` SET `qty` = `qty` + '" + grn_material_qty_value + "' WHERE `material_id` = '" + material_id + "'");
                                    insert = false;

                                }

                            }

                            if (insert) {

                                MySQL.executeIUD("INSERT INTO `stock` (`material_id`,`qty`) VALUES ('" + material_id + "', '" + grn_material_qty_value + "')");

                            }

                        }

                        for (int i = 0; i < dtm.getRowCount(); i++) {

                            String m_id = String.valueOf(jTable1.getValueAt(i, 1));
                            String grn_m_qty = String.valueOf(jTable1.getValueAt(i, 3));
                            String grn_m_uprice = String.valueOf(jTable1.getValueAt(i, 4));

                            ResultSet resultSet2 = MySQL.executeSearch("SELECT * FROM `stock` WHERE `material_id` = '" + m_id + "'");

                            String stock_id = null;

                            if (resultSet2.next()) {
                                stock_id = resultSet2.getString("id");
                            }

                            MySQL.executeIUD("INSERT INTO `grn_item` (`qty`,`price`,`material_id`,`stock_id`,`grn_id`) VALUES "
                                    + "('" + grn_m_qty + "', '" + grn_m_uprice + "', '" + m_id + "', '" + stock_id + "', '" + grn_number + "')");

                        }

                        Notifications.getInstance().show(Notifications.Type.SUCCESS, Notifications.Location.TOP_RIGHT, 3500l, "GRN saved Successfully!");
                        normalReset();
                        fullReset();
                        generateGRNId();
                        products.loadStock();

                    }

                } catch (SQLException e) {
                    e.printStackTrace();
                } catch (Exception e) {
                    e.printStackTrace();
                }

            }

        }
    }//GEN-LAST:event_savegrnActionPerformed

    private void clearAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearAllActionPerformed
        // reset
        normalReset();
        fullReset();
    }//GEN-LAST:event_clearAllActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addtogrn;
    private javax.swing.JPanel backLogo;
    private javax.swing.JLabel back_label;
    private javax.swing.JFormattedTextField balance_label;
    private javax.swing.JButton clear;
    private javax.swing.JButton clearAll;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JFormattedTextField paying_price;
    private javax.swing.JFormattedTextField qty;
    private javax.swing.JButton savegrn;
    private javax.swing.JButton selectMaterial;
    private javax.swing.JButton selectSupplier;
    private javax.swing.JFormattedTextField total_lable;
    private javax.swing.JFormattedTextField unit_price;
    // End of variables declaration//GEN-END:variables

    // reset fields
    private void normalReset() {
        jLabel11.setText("");
        jLabel15.setText("");
        qty.setText("");
        unit_price.setText("");
        jTable1.setEnabled(true);
    }

    private void fullReset() {
        jLabel5.setText("");
        jLabel9.setText("");
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        dtm.setRowCount(0);
        total_lable.setText("0");
        paying_price.setText("");
        balance_label.setText("");
        selectSupplier.setEnabled(true);
    }

    // cal total
    private void calTotal() {

        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();

        double total = 0;

        for (int i = 0; i < dtm.getRowCount(); i++) {
            total += Double.parseDouble(String.valueOf(jTable1.getValueAt(i, 5)));
        }

        total_lable.setText(String.valueOf(total));

    }

    // enter the paying price and get a balance
    private void getBalance() {

        String paying = paying_price.getText();

        if (!paying.isEmpty()) {

            if (!paying.matches("^[0-9]+(\\.[0-9]{1,2})?$")) {
                Notifications.getInstance().show(Notifications.Type.ERROR, Notifications.Location.TOP_RIGHT, 3500l, "Invalid GRN Material Price!");
            } else {

                Double payingValue = Double.parseDouble(paying);
                Double totalValue = Double.parseDouble(total_lable.getText());

                Double balance = totalValue - payingValue;
                balance_label.setText(String.valueOf(balance));

            }

        } else {
            paying_price.setText("0");

            Double payingValue = Double.parseDouble(paying_price.getText());
            Double totalValue = Double.parseDouble(total_lable.getText());

            Double balance = totalValue - payingValue;
            balance_label.setText(String.valueOf(balance));
        }

    }

}
