/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.awt.Image;
import java.awt.Toolkit;
import model.JpanelLoader;
import raven.toast.Notifications;

/**
 *
 * @author User
 */
public class Supplier_Registration extends javax.swing.JFrame {

    JpanelLoader jpload = new JpanelLoader();

    /**
     * Creates new form Supplier_Registration
     */
    public Supplier_Registration() {
        initComponents();
        this.setExtendedState(Home.MAXIMIZED_BOTH);
        init();

        // set notification position
        Notifications.getInstance();

        // add a icon image
        Image image = Toolkit.getDefaultToolkit().getImage(this.getClass().getResource("/resources/icon.png"));
        this.setIconImage(image);
    }

    private void init() {
        // panel load
        Supplier_Registration_Panel supplier_Registration_Panel = new Supplier_Registration_Panel();
        jpload.jPanelLoader(register_panel_loader, supplier_Registration_Panel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        register_panel_loader = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1260, 1222));
        setResizable(false);

        register_panel_loader.setBorder(null);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(register_panel_loader, javax.swing.GroupLayout.DEFAULT_SIZE, 1260, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(register_panel_loader, javax.swing.GroupLayout.DEFAULT_SIZE, 620, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane register_panel_loader;
    // End of variables declaration//GEN-END:variables
}
